EscolaLMS/sdk

src/react/context/defaults.ts, src/react/context/index.tsx, src/react/context/types.ts, src/services/request.ts
=> essential sdk changes

src/react/context/defaults.ts, src/react/context/index.tsx, src/react/context/types.ts, src/services/consultations.ts, src/services/courses.ts, src/types/api.ts
Mentions STAR-406
Mentions STAR-609
=> Fetch consultations list and single consultation

src/types/api.ts
=> new types for cart products

src/types/api.ts
=> Types for productable courses and consultations

src/react/context/defaults.ts, src/react/context/index.tsx, src/react/context/types.ts, src/services/webinars.ts, src/types/api.ts
=> Fetch webinars from admin panel

src/react/context/defaults.ts, src/react/context/index.tsx, src/react/context/types.ts, src/services/consultations.ts, src/types/api.ts
Mentions STAR-415
Mentions STAR-408
=> Fetch user consultations, book date for consultation

src/types/api.ts
=> New type for consultations

src/react/context/defaults.ts, src/react/context/index.tsx, src/react/context/types.ts, src/services/cart.ts
Mentions STAR-611
Mentions STAR-441
=> Quantity handler for cart

src/react/context/defaults.ts, src/react/context/index.tsx, src/react/context/types.ts, src/services/events.ts, src/types/api.ts
=> Fetch events

src/types/api.ts
=> Categories param for consultations and courses

src/types/api.ts
=> last_page type for paginated models

src/types/api.ts
=> New img type for product

src/react/context/defaults.ts, src/react/context/index.tsx, src/react/context/types.ts, src/services/cart.ts
=> Missing products in cart endpoint

src/react/context/index.tsx, src/react/context/types.ts, src/services/auth.ts, src/types/api.ts
=> Update user types, update files with default prettier

src/react/context/index.tsx, src/react/context/tags.tsx, src/react/context/tutors.tsx
@qunabu in the next PR I will prepare tests for these contexts, is that ok?
=> LMSDEMO-366 - Context Tags/Tutors

tests/context/courses.test.tsx, tests/test_server/courses.ts
https://escl24.atlassian.net/browse/LMSDEMO-291
=> Fix failing tests

src/types/api.ts
Update necessary to make types match the actual API response
=> Update API types

package.json, src/react/context/bookmark_notes.tsx, src/react/context/defaults.ts, src/react/context/index.tsx, src/react/context/types.ts, src/services/bookmarks_notes.ts, src/types/api.ts
=> bookmark notes

src/react/hooks/useCart.ts, src/react/hooks/useProgress.ts, tests/hooks/useCart.test.ts, tests/hooks/useProgress.test.ts, tests/test_server/cart.ts, tests/test_server/index.ts
Add useCart hook.
Add useProgress hook.
=> Hooks for cart and progress.

src/react/context/attendances.tsx, src/react/context/defaults.ts, src/react/context/index.tsx, src/react/context/types.ts, src/services/student/schedule.ts, src/types/api.ts, tests/context/schedule.test.tsx, tests/test_server/index.ts, tests/test_server/schedule.ts
TODO: Add tests for scheduleTutors and Subjects
=> Fetch attendances, add schedule tests, fix for schedules

src/react/context/index.tsx, src/services/stationary_events.ts
Add token to getStationaryEvent.
https://escl24.atlassian.net/browse/WELLMS-347
=> [WELLMS-347-16] Add token to getStationaryEvent. 

src/types/api.ts
=> Add deadline to Webinar type.

src/react/context/index.tsx, src/react/context/types.ts, src/services/webinars.ts
Change type from Event to Webinar in user webinars.
https://escl24.atlassian.net/browse/WELLMS-317
=> [WELLMS-317] Change type from Event to Webinar in user webinars.

src/react/context/defaults.ts, src/react/context/index.tsx, src/react/context/types.ts, src/services/courses.ts
Change fetchMyAuthoredCourses to paginated mode.
=> Change fetchMyAuthoredCourses to paginated mode.

src/react/context/index.tsx, src/utils/course.ts
Fix bug with first topic when index is 0.
=> [WELLMS-400] Fix bug with first topic when index is 0.

src/react/context/defaults.ts, src/react/context/index.tsx, src/react/context/questionnaires.tsx, src/react/context/types.ts, src/services/questionnaire.ts, src/types/api.ts
Add fetchQuestionnaireStarsByModel function.
=> Add fetchQuestionnaireStarsByModel function.

src/services/notify.ts, src/types/api.ts
Add notyficationTokens function in service.
Update Lesson type.
=> Add notyficationTokens function in service.

src/react/context/index.tsx, src/react/context/types.ts, src/services/certificates.ts, src/types/api.ts
=> Add CertificateParams type

package.json, src/react/context/defaults.ts, src/react/context/dictionary/dictionariesAccess.tsx, src/react/context/dictionary/dictionariesWord.tsx, src/react/context/dictionary/dictionariesWords.tsx, src/react/context/dictionary/dictionariesWordsCategories.tsx, src/react/context/index.tsx, src/react/context/types.ts, src/services/dictionary.ts, src/types/api.ts
Fix dictionaries functionality
=> Fix dictionaries functionality

src/react/context/dictionary/dictionariesWords.tsx, src/types/api.ts
Add abort param in dictionary words
=> Add abort param in dictionary words

src/types/api.ts
Add types for revenuecat in product.
=> Add types for revenuecat in product.
